baseURL = "https://arjshiv.github.io/public"
languageCode = "en-us"
title = "Arjun Kannan"
theme = "hugo-resume"

[params]
    firstName = "Arjun"
    lastName = "Kannan"
    address = "New York, NY"
    phone = "1-720-326-4767"
    contactNote = "Engineering and Product Executive"
    profileImage = "images/arjun.png"
    email = "email@domain.com"
    description = "Blah"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
#    showProjects = true
#    showOpenSource = true
#    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/arj_shiv/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[params.google.analytics]
    trackerID = "XX-123446-01"
