baseURL = "/"
languageCode = "en-us"
title = "Arjun Kannan"
theme = "hugo-resume"

[params]
    firstName = "Arjun"
    lastName = "Kannan"
    address = "New York, NY"
    phone = "1-720-326-4767"
    contactNote = "Product + Engineering Executive"
    profileImage = "images/arjun.png"
    email = "me@arjunkannan.com"
    description = "Arjun Kannan"
    favicon = "images/favicon.ico"
    # what sections
#    showSkills = true
#    showProjects = true
#    showOpenSource = true
#    showPublications = true
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/arjun-kannan"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/arj_shiv/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/arjshiv/"

[params.google.analytics]
    trackerID = "UA-117789770-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
